package com.bms.bankmanagementsystem.Entity;

import javax.persistence.*;
import java.util.Date;

@Entity
public class Report {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long reportId;

    private String reportType;         // Type of report, e.g., "Transaction Report"
    private Date reportDate;           // Date when the report is generated
    private String reportDetails;      // Details or description of the report

    // Many-to-One relationship: Many reports can be generated by one employee
    @ManyToOne
    @JoinColumn(name = "employeeId", nullable = false)  // Foreign key to Employee entity
    private Employee employee;

    // Getters and Setters

    public Long getReportId() {
        return reportId;
    }

    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    public String getReportType() {
        return reportType;
    }

    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    public Date getReportDate() {
        return reportDate;
    }

    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }

    public String getReportDetails() {
        return reportDetails;
    }

    public void setReportDetails(String reportDetails) {
        this.reportDetails = reportDetails;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    // Constructors

    public Report(Long reportId, String reportType, Date reportDate, String reportDetails, Employee employee) {
        super();
        this.reportId = reportId;
        this.reportType = reportType;
        this.reportDate = reportDate;
        this.reportDetails = reportDetails;
        this.employee = employee;
    }

    public Report() {
        super();
    }

    // toString Method

    @Override
    public String toString() {
        return "Report [reportId=" + reportId + ", reportType=" + reportType + ", reportDate=" + reportDate
                + ", reportDetails=" + reportDetails + ", employee=" + employee + "]";
    }
}
